---
- hosts: minecraft
  become: yes
  vars:
    update_server: yes
    agree_to_eula: "true" #Do you agree to the eula? See https://account.mojang.com/documents/minecraft_eula
  roles:
    - minecraft
