---
- hosts: minecraft
  remote_user: vagrant
  become: yes
  vars:
    update_server: yes
    agree_to_eula: "true" #Do you agree to the eula? See https://account.mojang.com/documents/minecraft_eula
    install_location: "/home/minecraft"
    minecraft_version: 1.8.9
    minecraft_url: "https://s3.amazonaws.com/Minecraft.Download/versions/{{ minecraft_version }}/minecraft_server.{{ minecraft_version }}.jar"
    minecraft_sha256sum: "c18e4245073aaff580eb7359902f0251436568b1647a9e443a924cdb73fa8312"
    java_options: "-Xms512M -Xmx512M -jar {{ install_location }}/minecraft_server.{{ minecraft_version }}.jar nogui" #Change the Xms and Xmx values base on the resources of your server.
  roles:
    - minecraft
