---
- name: Get and install the Docker binary
  get_url: url={{ docker_url }}
           dest=/usr/bin/docker-{{ docker_version }}
           sha256sum={{ docker_sha256sum }}
           owner=root
           group=root
           mode=0755

- name: Symlink docker-{{ docker_version}} to docker
  file: src=/usr/bin/docker-{{ docker_version }}
        dest=/usr/bin/docker
        force=yes
        state=link

- name: Install Docker systemd
  template: src=docker.service.j2
            dest=/etc/systemd/system/docker.service
            owner=root
            group=root
            mode=0755
  notify: Restart Docker

- name: Start Docker
  service: name=docker
           state=started
           enabled=yes
  when: docker_provisioned is defined
