spawn_protection: 16
max_tick_time: 60000
generator_settings: ""
force_gamemode: "false"
allow_nether: "true"
gamemode: 0
enable_query: "false"
player_idle_timeout: 0
difficulty: 1
spawn_monsters: "true"
op_permission_level: 4
resource_pack_hash: ""
announce_player_achievements: "true"
pvp: "true"
snooper_enabled: true
level_type: "DEFAULT"
hardcore: "false"
enable_command_block: "false"
max_players: 20
network_compression_threshold: 256
max_world_size: 29999984
server_port: 25565
server_ip: ""
spawn_npcs: "true"
allow_flight: "false"
level_name: "world"
view_distance: 10
resource_pack: ""
spawn_animals: "true"
white_list: "false"
generate_structures: "true"
online_mode: "true"
max_build_height: 256
level_seed: ""
use_native_transport: "true"
enable_rcon: "false"
motd: "A Minecraft Server"
