---
- name: Update system
  apt: upgrade=full
        update-cache=yes
        cache_valid_time=86400
  when: update_server is defined

- name: Create minecraft user
  user: name=minecraft
        shell=/bin/nologin
        createhome=yes

- name: Install openjdk7
  apt: name=openjdk-7-jre
       state=present

- name: Download minecraft.jar
  get_url: url={{ minecraft_url }}
           dest={{ install_location }}/minecraft_server.{{ minecraft_version }}.jar
           owner=minecraft
           group=minecraft
           mode=0644

- name: Install eula and server.properties
  template: src={{ item }}.j2
            dest={{ install_location }}/{{ item }}
            owner=minecraft
            group=minecraft
            mode=0644
  with_items:
    - eula.txt
    - server.properties
  notify: Restart Minecraft

- name: Install whitelist
  template: src=whitelist.json.j2
            dest={{ install_location }}/whitelist.json
            owner=minecraft
            group=minecraft
            mode=0644
  when: white_list_include is defined and white_list == "true"
  notify: Restart Minecraft

- name: Install systemd script
  template: src=minecraft.service.j2
            dest=/etc/systemd/system/minecraft.service
            owner=root
            group=root
            mode=0644
  notify: Restart Minecraft

- name: Install logrotate
  template: src=logrotate.j2
            dest=/etc/logrotate.d/minecraft
            owner=root
            group=root
            mode=0644
