---
- name: Update system
  apt: upgrade=full
  when: update_server is defined

- name: Create minecraft user
  user: name=minecraft
        shell=/bin/nologin
        createhome=yes

- name: Install openjdk7
  apt: name=openjdk-7-jre
       state=present

- name: Download minecraft.jar
  get_url: url={{ minecraft_url }}
           dest={{ install_location }}/minecraft_server.{{ minecraft_version }}.jar
           owner=minecraft
           group=minecraft
           mode=0644

- name: Install eula.txt
  template: src=eula.txt.j2
            dest={{ install_location }}/eula.txt
            owner=minecraft
            group=minecraft
            mode=0644

- name: Install systemd script
  template: src=minecraft.service.j2
            dest=/etc/systemd/system/minecraft.service
            owner=root
            group=root
            mode=0644
  notify: Start Minecraft

- name: Install logrotate
  template: src=logrotate.j2
            dest=/etc/logrotate.d/minecraft
            owner=root
            group=root
            mode=0644
