---
- hosts: docker-minecraft
  become: yes
  vars:
    docker_provisioned: yes
    docker_options: "-s aufs"
  roles:
    - common
    - docker
  tasks:
    - name: Deploy Minecraft Docker container
      docker:
        name: minecraft
        image: corbanr/minecraft:1.10
        state: reloaded
        pull: missing
        restart_policy: always
        restart_policy_retry: 10
        ports:
        - "25565:25565"
        env:
            JAVA_XMS: "1024m"
            JAVA_XMX: "1024m"
